### ISSUE TITLE
关于Latex的渲染问题...

### ISSUE THREAD

**Issue by Cansult** [miccall/hexo-theme-Mic_Theme#27]
这个主题是不是不资瓷Latex啊...找了好多办法并没有什么卯月...
**主题很好但是**没有Latex怎么写公式啊...

**Comment by miccall** [comment]
@Cansult  真的不好意思，这一点我是没考虑进去，尽情关注下一个版本~

**Comment by Cansult** [comment]
OK [A determined look]
