### ISSUE TITLE
有关disqus模块

### ISSUE THREAD

**Issue by royyoung388** [miccall/hexo-theme-Mic_Theme#4]
请问在disqus模块，有一个链接，还有上下文是怎么做到的？？

我注册了一个disqus账号，也添加了域名，但是打开自己的博客，下面的disqus模块和你的一模一样，没有改变。

我怎么才能制定disqus模块？

@miccall

**Comment by miccall** [comment]
@royyoung388  在配置文件中 75行 shortname 属性 改成自己的就行

**Comment by royyoung388** [comment]
感谢，我之前改了，但是没成功，今天重新下载又操作了一下就好了，玄学。。。。
对于其他文章的链接是怎么做到的？需要在disqus上面发表吗？

**Comment by miccall** [comment]
@royyoung388  我没懂你的意思 文章都有唯一的地址 disqus自动匹配的

**Comment by royyoung388** [comment]
懂了，感谢
