### ISSUE TITLE
文章链接跳转问题？

### ISSUE THREAD

**Issue by LeoCHANGcn** [miccall/hexo-theme-Mic_Theme#53]
比如我在一篇文章的md文件里想给出另一个文章的链接，有设么好办法吗？比如`[this article](./../_post/test.md)`的形式
还是说只能给部署后的链接啊

**Comment by miccall** [comment]
不能这样写，这样的写法是错误的。你只能先把前一篇文章提交了，在地址栏复制文章地址才行
@LeoCHANGcn

**Comment by LeoCHANGcn** [comment]
好的谢谢
